pipeline {
    agent any

    environment {
        AWS_CRED              = 'aws_jr10_wanda'
        ECR_REPOSITORY        = credentials('job_post_api_ecr')
        AWS_ID                = credentials('aws_id')
        IMAGE_TAG             = 'latest'
        IMAGE_NAME            = 'job_post_api'
    }

    stages {    
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker stop $(docker ps -a -q)'
                    sh 'docker rm $(docker ps -a -q)'
                    sh "docker build -t ${IMAGE_NAME} -f ./Dockerfile ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker run -p 4000:4000 --network='host' -d ${IMAGE_NAME}"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://${AWS_ID}.dkr.ecr.us-east-1.amazonaws.com", "ecr:us-east-1:${AWS_CRED}") {
                        dockerImage = docker.image("${IMAGE_NAME}:${IMAGE_TAG}")
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
