pipeline {
    agent any

    environment {
        AWS_CRED              = 'aws_jr10_wanda'
        ECR_REPOSITORY        = credentials('job_post_api_ecr')
        AWS_ID                = credentials('aws_id')
        IMAGE_TAG             = 'latest'
        IMAGE_NAME            = 'job-post-api'
    }

    stages {    
        stage('Building image') {
            steps {
                script {
                    dockerImage = docker.build "${ECR_REPOSITORY}"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withAWS(credentials: AWS_CRED, region: 'us-east-1'){
                    script {
                        sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ID}.dkr.ecr.us-east-1.amazonaws.com"
                        sh "docker push ${AWS_ID}.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_NAME}:latest"
                    }
                }
            }
        }
        

        stage('Stop Previous Containers') {
            steps {
                    sh "docker ps -f name=${IMAGE_NAME} -q | xargs --no-run-if-empty docker container stop"
                    sh "docker container ls -a -fname=${IMAGE_NAME} -q | xargs -r docker container rm"
                }
        }
        

        stage('Docker Run') {
            steps{
                script {
                    sh "docker run -d -p 4000:4000 --rm --name ${IMAGE_NAME} ${AWS_ID}.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_NAME}:latest"
                }
            }
        }

    }
}
