pipeline {
    agent {
        docker {
            image 'node:16'
            args '-u root' // Run as root user to perform Docker operations
        }
    }

    environment {
        AWS_CRED              = 'aws_jr10_wanda'
        ECR_REPOSITORY        = credentials('job_post_api_ecr')
        AWS_ID                = credentials('aws_id')
        IMAGE_TAG             = 'latest'
        IMAGE_NAME            = 'job_post_api'
    }

    stages {    
        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME} -f ./Dockerfile ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://${AWS_ID}.dkr.ecr.us-east-1.amazonaws.com", "ecr:us-east-1:${ECR_REPOSITORY}") {
                        dockerImage = docker.image("${IMAGE_NAME}:${IMAGE_TAG}")
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
